'UTILITY AND CONFIG'
class "GameConfig<static>" as GameConfig{
  + int MAX_TIME
  + int FIREBALL_MULTIPLIER
  + int FIREBALL_INCREMENT
  + int FIREBALL_THRESHOLD
  + int BACKBOARD_FREQUENCY
  + Dictionary<BonusRarity, RarityMetadata> RARITY_METADATA
}
enum BonusRarity{
  Common
  Uncommon
  Rare
  Epic
  Legendary
}
struct RarityMetadata{
  + Color color
  + int threshold
  + int pointBonus
}

enum BasketballShot{
  Perfect
  Backboard
  HoopTouch
  Miss
}
class "GameState<pure class>" as GameState{
  + int score
  + int remainingTime
  + int fireballValue
  
  + event OnScoreChange
  + event OnRemainingTimeChange
  + event OnTimeEnd
  + event OnFireballChange
  + event OnFireballEnable
  + event OnFireballDisable
  
  + void AddTime(int time)
  + void RemoveTime(int time)
  + void AddFireball(int value)
  + void ResetFireball()
  + void AddScore(int score)
  + void ResetScore()
  - void Fireball(bool enable)
}
class "GameplayController<singleton>" as GameplayController{
  + GameplayController Instance
  
  + event OnGameStart
  + event OnGameEnd

  + void StartGame()
  + void EndGame()
  - void TimeStep()
  
}

'PLAYER CLASSES'
class InputHandler{
  - void OnMouseToggle()
  - void OnJumpPerformed()
  - voic OnThrowBallPerformed()
}
class PlayerController{
  + void Move()
  + void Look()
  + void Jump()
  + void ThrowBall()
}

'UI ELEMENTS'
class GameplayUI{
  - TMP TMP_Time
  - TMP TMP_FireballMeter
  - TMP TMP_FireballStatus
  - TMP TMP_Score
  
  + void SetTimeLeft(int time)
  + void SetScore(int score)
  + void SetFireballValue(int value)
  + void SetFireballEnable()
  + void SetFireballDisable()
}
class RewardUI{
  - TMP finalScore
  
  + void SetScore(int score)
}


'BASKET RELATED CLASSES'
class BasketballHoop{

}
class BasketballBoard{
  - TMP TMP_bonus
  - rollFrequency
  + int PointBonus
  
  + BonusRarity SelectRarity()
  + void UpdateText(BonusRarity)
  + void SelectApplyRarity()
}
class BasketballFactory{
  //WIP
}
class Basketball{
  - int ball_points
  - void OnCollisionEnter() 
}
note left of Basketball::OnCollision()
- Detect hoop collision
- Detect board collision
- Detect scored
end note









InputHandler -> PlayerController
PlayerController --> BasketballFactory

GameplayController --> GameState
GameState ..> GameConfig
GameConfig -> BonusRarity
GameConfig *-- RarityMetadata

GameplayUI ..> GameplayController
GameplayUI ..> GameConfig
RewardUI ..> GameplayController

BasketballFactory -> BasketballShot
BasketballFactory ..> Basketball

Basketball ..> BasketballHoop
Basketball ..> BasketballBoard
Basketball ..> GameplayController