struct SCN_MainMenu
struct SCN_Gameplay


class "GameConfig<static>" as GameConfig {
  + int MAX_TIME
  ...
}
class GameplayUI{
  - bool active = True
}
class RewardUI{
  - bool active = False
}
class Options{
  - Slider maxTime
  + void SetGameMaxTime()
}
class ButtonEvents{
  + void SwitchScene(string targetScene)
  + void SwitchToGameplay(string gameplay_scene)
  + void SwitchToMainMenu(string main_menu_scene)
  + void QuitGame()
}
class "BackgroundMusic<singleton>" as BackgroundMusic{
  - AudioSource BGM
  + void PlayFromStart()
  + void Stop()
}
circle Exit

ButtonEvents ..> BackgroundMusic
SCN_Gameplay --> GameplayUI
SCN_Gameplay --> RewardUI
SCN_MainMenu --> SCN_Gameplay : play
SCN_MainMenu --> Exit : quit
SCN_MainMenu -> Options

RewardUI ..> SCN_Gameplay : play
RewardUI ..> SCN_MainMenu : back
GameplayUI ..> SCN_MainMenu : back
Options ..> GameConfig

