'UTILITY AND CONFIG'
class "GameConfig<static>" as GameConfig{
  + int MAX_TIME
  + int FIREBALL_MULTIPLIER
  + int FIREBALL_INCREMENT
  + int FIREBALL_THRESHOLD
  + int BACKBOARD_FREQUENCY
  + Dictionary<BonusRarity, RarityMetadata> RARITY_METADATA
}
enum BonusRarity{
  Common
  Uncommon
  Rare
  Epic
  Legendary
}
struct RarityMetadata{
  + Color color
  + int threshold
  + int pointBonus
}
class "Ballistics<static>" as Ballistics{
  + bool, Vector3 SolveArcTargetAngle(Vector3 s, Vector3 t, float a, float g)
  + Vector3 ReflectPointAcrossPlane(Vector3 p, Vector3 plane, Vector3 normal)
}
class "RandomPoint<static>" as RandomPoint{
  + Vector3 RandomPointInBox(GameObject g1, GameObject g2)
  + Vector3 RandomPointInBox(Vector3 g1, Vector3 g2)
  
}
enum BasketballShot{
  Perfect
  Backboard
  HoopTouch
  Miss
}


class "GameState<pure class>" as GameState{
  + int score
  + int remainingTime
  + int fireballValue
  
  + event OnScoreChange
  + event OnRemainingTimeChange
  + event OnTimeEnd
  + event OnFireballChange
  + event OnFireballEnable
  + event OnFireballDisable
  
  + void AddTime(int time)
  + void RemoveTime(int time)
  + void AddFireball(int value)
  + void ResetFireball()
  + void AddScore(int score)
  + void ResetScore()
  - void Fireball(bool enable)
}
class "GameplayController<singleton>" as GameplayController{
  + GameplayController Instance
  
  + event OnGameStart
  + event OnGameEnd

  + void StartGame()
  + void EndGame()
  - void TimeStep()
  
}

'PLAYER CLASSES'
class InputHandler{
  - void OnMouseToggle()
  - void OnJumpPerformed()
  - voic OnThrowBallPerformed()
}
class PlayerController{
  + void Move()
  + void Look()
  + void Jump()
  + void ThrowBall()
}

'UI ELEMENTS'
class GameplayUI{
  - TMP TMP_Time
  - TMP TMP_FireballMeter
  - TMP TMP_FireballStatus
  - TMP TMP_Score
  
  + void SetTimeLeft(int time)
  + void SetScore(int score)
  + void SetFireballValue(int value)
  + void SetFireballEnable()
  + void SetFireballDisable()
}
class RewardUI{
  - TMP finalScore
  
  + void SetFinalScore(int score)
}
class FloaterTextController{
  - TMP TMP_BallPoints
  - float autoDisable
  - bool playOnStart
  - GameObject _rotateTowards
  - bool autoRotateTowards
  
  + void DisplayPoints(int points)
}
note left of FloaterTextController::TMP_BallPoints
- animated no auto loop
end note
note left of FloaterTextController::autoRotateTowards
- rotate text to object on update
end note
class ScoreFXController{
  - ParticleSystem particleSystem
  
  + void PlayFX();
}


'BASKET RELATED CLASSES'
class BasketballHoop{

}
class BasketballBoard{
  - TMP TMP_bonus
  - int rollFrequency
  + int PointBonus
  
  + BonusRarity SelectRarity()
  + void UpdateText(BonusRarity)
  + void SelectApplyRarity()
}
class BasketballFactory{
  - GameObject basketballPrefab
  - Vector3 spawnOffset
  
  + GameObject CreateBasketball()
  + GameObject CreateBasketball(Vector3 position, Quaternion rotation)
  + GameObject DelayDestroy(GameObject o, float delay)
}
class BallisticLauncher{
  + Transform Target
  + Transform ReflectAgainst
  + float ArrivalAngle
  
  + bool LaunchGameObject(GameObject o, LaunchMode m, float forward_offset)
  - bool LaunchDirect(GameObject o)
  - bool LaunchReflect(GameObject o, float forward_offset)
  
  + static bool LaunchDirect(...)
  + static bool LaunchReflect(...)
}
enum LaunchMode {
  Direct
  Reflect
}
class Basketball{
  + int BallPoints
  + float BallDiameter
  - bool isValid
  - void OnCollisionEnter() 
  - void OnTriggerEnter()
}
note left of Basketball::OnCollisionEnter()
- Detect hoop collision
- Detect board collision
end note
note left of Basketball::OnTriggerEnter()
- Validation trigger
- Score trigger
end note









InputHandler -> PlayerController
PlayerController --> BasketballFactory

GameplayController --> GameState
GameState ..> GameConfig
GameConfig -> BonusRarity
GameConfig *-- RarityMetadata

GameplayUI ..> GameplayController
GameplayUI ..> GameConfig
RewardUI ..> GameplayController

BasketballFactory ..> Basketball

Basketball ..> BasketballHoop
Basketball ..> BasketballBoard
Basketball ..> GameplayController
Basketball -> BasketballShot
Basketball ...> FloaterTextController
Basketball ...> ScoreFXController


BallisticLauncher --> Ballistics
BallisticLauncher -> LaunchMode




















