'UTILITY AND CONFIG'
class "GameConfig<static>" as GameConfig{
  + int MAX_TIME
  + int FIREBALL_MULTIPLIER
  + int FIREBALL_INCREMENT
  + int FIREBALL_THRESHOLD
  + int BACKBOARD_FREQUENCY
  + Dictionary<BonusRarity, RarityMetadata> RARITY_METADATA
}
enum BonusRarity{
  Common
  Uncommon
  Rare
  Epic
  Legendary
}
struct RarityMetadata{
  + Color color
  + int threshold
  + int pointBonus
}
class "Ballistics<static>" as Ballistics{
  + bool, Vector3 SolveArcTargetAngle(Vector3 s, Vector3 t, float a, float g)
  + Vector3 ReflectPointAcrossPlane(Vector3 p, Vector3 plane, Vector3 normal)
}
class "RandomPoint<static>" as RandomPoint{
  + Vector3 RandomPointInBox(GameObject g1, GameObject g2)
  + Vector3 RandomPointInBox(Vector3 g1, Vector3 g2)
  
}
enum "ShotType<flags>" as ShotType{
  None
  Perfect
  Backboard
  HoopTouch
}
enum ScoreType{
  Scored
  Missed
}


class GameState{
  + int Score
  + int RemainingTime
  + int FireballValue
  + bool FireballStatus
  
  + event OnRemainingTimeChange
  + event OnTimeStart
  + event OnTimeEnd
  
  + event OnFireballChange
  + event OnFireballEnable
  + event OnFireballDisable
  
  + event OnScoreChange
  
  + void AddTime(int time)
  + void RemoveTime(int time)
  + void StartTimer()
  - void TimeStep()
  
  + void AddFireball(int value)
  + void ResetFireball()
  
  + void AddScore(int score)
  + void ResetScore()
}
class "ScoreController<singleton>" as ScoreController{
  + ScoreController Instance
  
  + event OnGameStart
  + event OnGameEnd

  + void StartGame()
  + void EndGame()
  - void TimeStep()
  
}

'INPUT'
class InputHandler{
  - IM_InputMapping playerControls
  - Camera mainCamera
  - bool primaryContact
  
  + event OnStartTouch
  + event OnEndTouch

  + event OnJump
  + event OnMove
  + event OnLook
  + event OnThrow
  
  + event OnSwipeThrowUpdate;
  + event OnSwipeThrowStarted;
  + event OnSwipeThrowSuccessful;
  + event OnSwipeThrowCanceled;

  - void JumpPerformed()

  - void PrimaryContactStart()
  - void PrimaryContactEnd()
  
    + Vector3 Primary3DPosition()
  + Vector2 Primary2DPosition()
  + Vector3 ScreenToWorld(Camera camera, Vector3 position)
  + Vector2 ScreenToSquare(Vector2 pixel_position)
  
  - void MouseTogglePerformed()
  + void SetMouseVisibility(bool active)
  
  - voic ThrowPerformed()
  
  + void SwipeStart()
  + void SwipeUpdate(float distance)
  + void SwipeEnd(Vector2 direction, float distance)
  + void SwipeCancel()
  

}
class SwipeDetection{
  - Vector2 startPosition
  - float startTime
  - Vector2 endPosition
  - float endTime
  
  - float minimumDistance
  - float maximumTime
  - float directionThreshold
  - float clampMaximumDistance
  
  - bool trailEnabled
  - TrailRenderer trail
  
  - void SwipeStart(Vector2 position, float time)
  - void SwipeEnd(Vector2 position, float time)
  - void DetectSwipe()
}

'PLAYER CLASSES'
class PlayerController{
  - GameObject head
  - CharacterController characterController
  
  - float movementSpeed
  - float rotationSpeed
  - float jumpForce
  - float gravity
  - float throwFactor
  
  - Basketball thrownBall
  
  + void Move()
  + void Look()
  + void Jump()
  + void Teleport(Vector3 position, Vector3 look_at)
  
  + void ThrowBallAuto()
  
  - void OnThrownBallScored(Basketball basketball)
  - void OnThrownBallMiss(Basketball basketball)
  - void OnThrownBallDespawn(Basketball basketball)
  + void SwipeThrowBall(Vector2 direction, float power)

}

'UI ELEMENTS'
class GameplayUI{
  - TMP TMP_Time
  - TMP TMP_FireballMeter
  - TMP TMP_FireballStatus
  - TMP TMP_FireballMultiplier
  - TMP TMP_Score
  - TMP TMP_PowerMeter
  - Slider Slider_PowerMeter
  - Slider Slider_FireballMeter
  - InputHandler inputHandler
  
  - void SetTimeLeft(int time)
  - void SetScore(int score)
  - void SetFireballValue(int value)
  - void SetFireballEnable()
  - void SetFireballDisable()
  - void SetFireballMultiplierValue(int value)
  - void SetFireballMultiplierVisibility(bool visibility)
  - void SetPowerValue(float value)
  - void ResetPowerValue()
}
note left of GameplayUI::inputHandler
to retrieve slide data
end note
class RewardUI{
  - TMP finalScore
  
  + void SetFinalScore(int score)
}


'BASKET RELATED CLASSES'
class BasketballBoard{
  - TMP TMP_bonus
  - int rollFrequency
  + int PointBonus
  
  + BonusRarity SelectRarity()
  + void UpdateText(BonusRarity)
  + void SelectApplyRarity()
}
class BasketballFactory{
  - GameObject basketballPrefab
  - Vector3 spawnOffset
  
  + Basketball CreateBasketball()
  + Basketball CreateBasketball(Vector3 position, Quaternion rotation)
  + GameObject DelayDestroy(GameObject o, float delay)
}
class BasketballTracker{
  - CinemachineVirtualCamera ballCamera
  - Basketball trackedBall
  
  + void TrackBasketball(Basketball basketball)
  - void ResetTrackingCamera(Basketball despawned_ball)
}
class Basketball{
  - ParticleSystem fireTrail
  + int BallPoints
  + float BallDiameter
  
  - bool autoDelete
  - int lifetime
  
  - bool isValid
  - bool isLegal

  + event OnDespawn
  + event OnBasket
  + event OnMiss
  
  + void ActivateFireTrail()
  - void OnCollisionEnter() 
  - void OnTriggerEnter()
}
note left of Basketball::OnCollisionEnter()
- Detect hoop collision
- Detect board collision
end note
note left of Basketball::OnTriggerEnter()
- Validation trigger
- Score trigger
end note

'OTHER'
class BallisticLauncher{
  + Transform Target
  + Transform ReflectAgainst
  + float ArrivalAngle
  
  + AnimationCurve AimAssistCurve
  + float AimAssistRange
  
  + Vector3 AimAssist(Vector3 raw, Vector3 optimal, float range, AnimationCurve assist_curve)
  + bool LaunchGameObject(GameObject o, LaunchMode m, float forward_offset, float power)
  - bool LaunchDirect(GameObject o, float power)
  - bool LaunchReflect(GameObject o, float forward_offset, float power)
}
note right of BallisticLauncher::GraceCurve
Alters the power
makes it easier to score
end note
enum LaunchMode {
  Direct
  Reflect
}
class PlayerArea {
  - Vector3 size
  + Transform focalPoint
  
  + Vector3 GetPoint()
}
class FloaterTextController{
  - TMP TMP_BallPoints
  - Transform _rotateTowards
  - float autoDisable
  
  + void DisplayPoints(int points)
}
note left of FloaterTextController::TMP_BallPoints
- animated no auto loop
end note
note left of FloaterTextController::autoRotateTowards
- rotate text to object on update
end note
class ScoreFXController{
  - ParticleSystem particleSystem
  
  + void PlayFX();
}


SwipeDetection --> InputHandler

ScoreController ..> GameConfig
ScoreController ..> GameState
ScoreController ---> FloaterTextController
ScoreController ---> ScoreFXController

GameState ..> GameConfig
GameConfig -> BonusRarity
GameConfig *-- RarityMetadata

PlayerController o-- BasketballFactory
PlayerController o-- BallisticLauncher
PlayerController o-- BasketballTracker
PlayerController o-- PlayerArea

PlayerArea ..> RandomPoint

PlayerController o-- InputHandler
PlayerController --> GameState
PlayerController ..> ScoreController

BallisticLauncher --> Ballistics
BallisticLauncher -l-> LaunchMode 

BasketballTracker o-- Basketball

BasketballFactory ..> Basketball

Basketball ..> BasketballBoard
Basketball -> ShotType
Basketball -> ScoreType


GameplayUI --> GameState
RewardUI --> GameState























